site_name: ActronAir Neo Integration
site_description: Documentation for the ActronAir Neo integration for Home Assistant
site_author: Ruaan Deysel
site_url: https://domalab.github.io/ha-actronair-neo/
repo_url: https://github.com/domalab/ha-actronair-neo
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - User Guide:
    - Installation: user/installation.md
    - Configuration: user/configuration.md
    - Usage: user/usage.md
    - Troubleshooting: user/troubleshooting.md
    - FAQ: user/faq.md
  - Developer Guide:
    - Architecture: developer/architecture.md
    - API Reference: developer/api_reference.md
    - Contributing: developer/contributing.md
    - Testing: developer/testing.md
    - Type System: developer/type_system.md
  - API Documentation:
    - Authentication: api/authentication.md
    - Commands: api/commands.md
    - Queries: api/queries.md
    - Responses: api/responses.md
  - Project:
    - Changelog: https://github.com/domalab/ha-actronair-neo/blob/main/CHANGELOG.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/domalab/ha-actronair-neo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/c5DvZ4e
  version:
    provider: mike
