name: ✨ Feature Request
description: Suggest a new feature or enhancement for the ActronAir Neo integration
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request

        Thank you for suggesting a new feature! This template is for requesting **new features or enhancements** for the ActronAir Neo integration.

        ## 📋 When to use this template:
        - ✅ You want to add new functionality to the integration
        - ✅ You have ideas for better automation or control options
        - ✅ You want to suggest UI/UX improvements
        - ✅ You want new sensors, controls, or services

        ## ❌ When NOT to use this template:
        - 🚫 **System Compatibility**: Your ActronAir system isn't working → Use "System Compatibility Request" template
        - 🚫 **Bug Reports**: Existing features are broken → Use "Bug Report" template

  - type: dropdown
    id: feature_category
    attributes:
      label: 🏷️ Feature Category
      description: "What type of feature are you requesting?"
      options:
        - "New entity type (sensor, switch, etc.)"
        - "Enhanced zone control"
        - "New climate features"
        - "Improved automation capabilities"
        - "Better system discovery"
        - "UI/UX improvements"
        - "Performance optimization"
        - "Configuration options"
        - "Analytics and reporting"
        - "Energy monitoring"
        - "Documentation improvement"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 📝 Feature Description
      description: "Clear description of the feature you'd like to see"
      placeholder: |
        **What feature would you like:**
        Add individual zone temperature sensors that show the actual temperature in each zone.

        **Why would this be useful:**
        It would help users monitor temperature differences between zones and create better automations.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 🎯 Use Case / Problem Solved
      description: "What problem does this feature solve? How would you use it?"
      placeholder: |
        **Problem:**
        Currently I can only see the main system temperature, but I want to know the temperature in each zone.

        **Use Case:**
        I want to create automations that adjust zone settings based on individual zone temperatures.

        **Benefit:**
        This would enable more precise climate control and energy efficiency.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: 💡 Proposed Solution
      description: "How do you think this feature should work?"
      placeholder: |
        **Implementation idea:**
        - Add new sensor entities: `sensor.zone_living_room_temperature`
        - Update temperature readings from each zone's sensor
        - Include zone-specific controls and settings

        **UI/UX:**
        - Show zone temperatures in the climate card
        - Add individual zone controls
        - Include in system diagnostics
      render: markdown
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: "Have you considered any alternative solutions or workarounds?"
      placeholder: |
        **Current workarounds:**
        - Using external temperature sensors
        - Manual monitoring through ActronAir app

        **Why they're not ideal:**
        - Requires additional hardware
        - Not integrated with the climate system
        - Manual monitoring is inconvenient
      render: markdown
    validations:
      required: false

  - type: input
    id: affected_systems
    attributes:
      label: 🌡️ Affected System Types
      description: "Which ActronAir system types would benefit from this feature?"
      placeholder: "All systems / Neo systems / Multi-zone systems"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: "How important is this feature to you?"
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my experience"
        - "High - Significantly impacts usability"
        - "Critical - Blocking important use cases"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: "Would you be willing to help implement this feature?"
      options:
        - label: "I'm willing to test development versions"
        - label: "I can help with documentation"
        - label: "I have programming skills and could contribute code"
        - label: "I can provide detailed requirements and feedback"

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Additional Context
      description: "Any other relevant information, mockups, or examples"
      placeholder: |
        - Screenshots or mockups of desired UI
        - Examples from other integrations
        - Technical considerations
        - Related feature requests
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: "Please confirm you have done the following:"
      options:
        - label: "I have searched existing issues to make sure this isn't a duplicate"
          required: true
        - label: "This feature request is for the ActronAir Neo integration"
          required: true
        - label: "I have clearly described the problem this feature would solve"
          required: true
