set_zone_state:
  name: Set Zone State
  description: Enable or disable a specific zone.
  fields:
    device_id:
      name: Device ID
      description: The ID of the Actron Air Neo device.
      required: true
      selector:
        device:
          integration: actron_air_neo
    zone_id:
      name: Zone ID
      description: The ID of the zone to control.
      required: true
      selector:
        text:
    enabled:
      name: Enabled
      description: Whether to enable or disable the zone.
      required: true
      selector:
        boolean:

set_away_mode:
  name: Set Away Mode
  description: Enable or disable away mode.
  fields:
    device_id:
      name: Device ID
      description: The ID of the Actron Air Neo device.
      required: true
      selector:
        device:
          integration: actron_air_neo
    away_mode:
      name: Away Mode
      description: Whether to enable or disable away mode.
      required: true
      selector:
        boolean: